services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - uploaded-data:/app/uploaded

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: resume123
      POSTGRES_DB: resumes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  n8n:
    image: n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=resumes
      - DB_POSTGRESDB_USER=resume
      - DB_POSTGRESDB_PASSWORD=resume123
    env_file:
      - ./.env
    ports:
      - "5678:5678"
    volumes:
      - uploaded-data:/app/uploaded
    depends_on:
      - postgres

  tika:
    image: apache/tika
    ports:
      - "9998:9998"

volumes:
  postgres-data:
  uploaded-data:
